In [2]:
import numpy as np

In [4]:
# Exercise 1: Create a 1D NumPy array of numbers from 0 to 9

arr = np.arange(10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Exercise 2: Convert 1D array to 2D

arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
# Exercise 3: Print Array Attributes
# Instructions: Print the following attributes of the array:

# The shape of the array.
# The number of array dimensions.
# The size of each element in bytes.

import numpy as np
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

print(my_array.shape)
print(my_array.ndim)
print(my_array.itemsize)



(4, 2)
2
2


In [ ]:
# Exercise 4: Create a 3×3 NumPy array of all True

arr = np.full((3,3), True)

In [16]:
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
# Exercise 5: Extract the documentation of NumPy’s arange() function
np.info(np.arange)


arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [21]:
# Exercise 6: Create a 1D array filled with zeros and another filled with ones

print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [22]:
# Exercise 7: Create a 1D array of 10 evenly spaced values between 5 and 50

np.linspace(5,50,10)

array([ 5., 10., 15., 20., 25., 30., 35., 40., 45., 50.])

In [23]:
# Exercise 8: Convert a Python list into a NumPy array

py_list = [1, 2, 3, 4, 5]

print(np.array(py_list))

[1 2 3 4 5]


In [24]:
# Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9

np.arange(10).nbytes

40

In [27]:
# Exercise 10: Reverse a 1D NumPy array
import numpy as np
arr = np.arange(10)[::-1]

arr

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [28]:
# Exercise 11: Create a 3×3 identity matrix

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# Exercise 12: Create a 4×4 array and extract its first row and last column
import random
arr = np.arange(0,16).reshape(4,4)
print(arr)
print(arr[0])
print(arr[-1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[0 1 2 3]
[12 13 14 15]


In [38]:
# Exercise 13: Extract Odd Rows and Even Columns

import numpy as np
sampleArray = np.array([
    [3, 6, 9, 12], 
    [15, 18, 21, 24], 
    [27, 30, 33, 36], 
    [39, 42, 45, 48], 
    [51, 54, 57, 60]
])


sampleArray[1::2, ::2]

array([[15, 21],
       [39, 45]])

In [43]:
# Exercise 14: Stack arrays horizontally

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# np.concatenate((a,b), axis = 0)
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [48]:
# Exercise 15: Slice the first two rows and first two columns from a 4×4 array

arr = np.arange(1,17).reshape(4,4)
print(arr)
arr[0:2, 0:2]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[1, 2],
       [5, 6]])

In [51]:
# Exercise 16: Replace all odd numbers in a NumPy array with -1

np.where(arr%2!=0, -1, arr)

arr[arr%2!=0]=-1

arr

array([[-1,  2, -1,  4],
       [-1,  6, -1,  8],
       [-1, 10, -1, 12],
       [-1, 14, -1, 16]])

In [52]:
# Exercise 17: Get the indices of non-zero elements in an array

sampleArray = np.array([
    [3, 6, 0, 12], 
    [15, 18, 21, 24], 
    [27, 30, 0, 36], 
    [39, 0, 45, 48], 
    [51, 54, 0, 60]
])
np.argwhere(arr)

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3]], dtype=int64)

In [53]:
# Exercise 18: Find the common items between two arrays

import numpy as np

a = np.array([1, 2, 3, 2, 8, 4, 2, 4])
b = np.array([2, 4, 5, 6, 8])

np.intersect1d(a,b)

array([2, 4, 8])

In [55]:
# Exercise 19: Perform arithmetic operations on two NumPy arrays element-wise

# Add two NumPy arrays element by element.
# Multiply two NumPy arrays element by element.

# mport numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)

print(a*b)

[5 7 9]
[ 4 10 18]


In [56]:
# Exercise 20: Matrix multiplication
# Write a code to compute the dot product of two NumPy arrays

import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.dot(a,b))

32
