In [1]:
import numpy as np
import random

In [11]:
arrr = np.random.randint(1,100,size=(3,3))

In [15]:
arrr

array([[ 8, 40, 69],
       [83, 28, 39],
       [31, 19, 15]])

In [7]:
# an array with nan values
a = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])

In [9]:
np.isnan(a).sum()

2

In [10]:
np.where(np.isnan(a))

(array([0, 1], dtype=int64), array([2, 1], dtype=int64))

In [14]:
np.array(arrr)[np.where(arrr > 50)]

array([69, 83])

In [16]:
arrr[np.where(arrr>20)]

array([40, 69, 83, 28, 39, 31])

In [17]:
arrr

array([[ 8, 40, 69],
       [83, 28, 39],
       [31, 19, 15]])

In [19]:
arrr[arrr>20]

array([40, 69, 83, 28, 39, 31])

In [21]:
np.where(arrr>20, 0, 1)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 1, 1]])

In [23]:
np.where(arrr>20, 20, arrr)

array([[ 8, 20, 20],
       [20, 20, 20],
       [20, 19, 15]])